lineas_with_data = {
    "linea1": {
        "Observatorio": {"neighbors": [("Tacubaya", 1262)]},
        "Tacubaya": {"neighbors": [("Observatorio", 1262), ("Juanacatlán", 1158), ("Patriotismo", 1133)], "intersections": ["linea7", "linea9"]},
        "Juanacatlán": {"neighbors": [("Tacubaya", 1158), ("Chapultepec", 973)]},
        "Chapultepec": {"neighbors": [("Juanacatlán", 973), ("Sevilla", 501)]},
        "Sevilla": {"neighbors": [("Chapultepec", 501), ("Insurgentes", 645)]},
        "Insurgentes": {"neighbors": [("Sevilla", 645), ("Cuauhtémoc", 793)]},
        "Cuauhtémoc": {"neighbors": [("Insurgentes", 793), ("Balderas", 409)]},
        "Balderas": {"neighbors": [("Cuauhtémoc", 409), ("Salto del Agua", 458), ("Juárez", 659)], "intersections": ["linea3"]},
        "Salto del Agua": {"neighbors": [("Balderas", 458), ("Isabel la Católica", 445), ("San Juan de Letrán", 292), ("Doctores", 564)], "intersections": ["linea8"]},
        "Isabel la Católica": {"neighbors": [("Salto del Agua", 445), ("Pino Suárez", 382)]},
        "Pino Suárez": {"neighbors": [("Isabel la Católica", 382), ("Merced", 745), ("Zócalo", 745), ("San Antonio Abad", 817)], "intersections": ["linea2"]},
        "Merced": {"neighbors": [("Pino Suárez", 745), ("Candelaria", 698)]},
        "Candelaria": {"neighbors": [("Merced", 698), ("San Lázaro", 866), ("Morelos", 1062), ("Fray Servando", 633)], "intersections": ["linea4"]},
        "San Lázaro": {"neighbors": [("Candelaria", 866), ("Moctezuma", 478), ("Ricardo Flores Magón", 907), ("Morelos", 1296)], "intersections": ["lineaB"]},
        "Moctezuma": {"neighbors": [("San Lázaro", 478), ("Balbuena", 703)]},
        "Balbuena": {"neighbors": [("Moctezuma", 703), ("Boulevard Puerto Aéreo", 595)]},
        "Boulevard Puerto Aéreo": {"neighbors": [("Balbuena", 595), ("Gómez Farías", 611)]},
        "Gómez Farías": {"neighbors": [("Boulevard Puerto Aéreo", 611), ("Zaragoza", 762)]},
        "Zaragoza": {"neighbors": [("Gómez Farías", 762), ("Pantitlán", 1320)]},
        "Pantitlán": {"neighbors": [("Zaragoza", 1320), ("Hangares", 1644), ("Puebla", 1380), ("Agrícola Oriental", 1409)], "intersections": ["linea5", "linea9", "lineaA"]},
    },
    "linea2": {
        "Cuatro Caminos": {"neighbors": [("Panteones", 1639)]},
        "Panteones": {"neighbors": [("Cuatro Caminos", 1639), ("Tacuba", 1416)]},
        "Tacuba": {"neighbors": [("Panteones", 1416), ("Cuitláhuac", 637), ("Refinería", 1295), ("San Joaquín", 1433)], "intersections": ["linea7"]},
        "Cuitláhuac": {"neighbors": [("Tacuba", 637), ("Popotla", 620)]},
        "Popotla": {"neighbors": [("Cuitláhuac", 620), ("Colegio Militar", 462)]},
        "Colegio Militar": {"neighbors": [("Popotla", 462), ("Normal", 516)]},
        "Normal": {"neighbors": [("Colegio Militar", 516), ("San Cosme", 657)]},
        "San Cosme": {"neighbors": [("Normal", 657), ("Revolución", 537)]},
        "Revolución": {"neighbors": [("San Cosme", 537), ("Hidalgo", 587)]},
        "Hidalgo": {"neighbors": [("Revolución", 587), ("Bellas Artes", 447), ("Guerrero", 702), ("Juárez", 251)], "intersections": ["linea3"]},
        "Bellas Artes": {"neighbors": [("Hidalgo", 447), ("Allende", 387)], "intersections": ["linea8"]}, #("Garibaldi / Lagunilla", 634), ("San Juan de Letrán", 456)], 
        "Allende": {"neighbors": [("Bellas Artes", 387), ("Zócalo", 602)]},
        "Zócalo": {"neighbors": [("Allende", 602), ("Pino Suárez", 745)]},
        "Pino Suárez": {"neighbors": [("Zócalo", 745), ("San Antonio Abad", 817), ("Isabel la Católica", 382), ("Merced", 745)], "intersections": ["linea1"]},
        "San Antonio Abad": {"neighbors": [("Pino Suárez", 817), ("Chabacano", 642)]},
        "Chabacano": {"neighbors": [("San Antonio Abad", 642), ("Viaducto", 774), ("Obrera", 1143), ("La Viga", 843), ("Lázaro Cárdenas", 1000), ("Jamaica", 1031)], "intersections": ["linea8", "linea9"]},
        "Viaducto": {"neighbors": [("Chabacano", 774), ("Xola", 490)]},
        "Xola": {"neighbors": [("Viaducto", 490), ("Villa de Cortés", 698)]},
        "Villa de Cortés": {"neighbors": [("Xola", 698), ("Nativitas", 750)]},
        "Nativitas": {"neighbors": [("Villa de Cortés", 750), ("Portales", 924)]},
        "Portales": {"neighbors": [("Nativitas", 924), ("Ermita", 748)]},
        "Ermita": {"neighbors": [("Portales", 748), ("General Anaya", 838), ("Mexicaltzingo", 1805), ("Eje Central", 895)], "intersections": ["linea12"]},
        "General Anaya": {"neighbors": [("Ermita", 838), ("Tasqueña", 1330)]},
        "Tasqueña": {"neighbors": [("General Anaya", 1330)]},
    },
    "linea3": {
        "Indios Verdes": {"neighbors": [("Deportivo 18 de Marzo", 1166)]},
        "Deportivo 18 de Marzo": {"neighbors": [("Indios Verdes", 1166), ("Potrero", 966), ("Lindavista", 1075), ("La Villa-Basílica", 570)], "intersections": ["linea6"]},
        "Potrero": {"neighbors": [("Deportivo 18 de Marzo", 966), ("La Raza", 1106)]},
        "La Raza": {"neighbors": [("Potrero", 1106), ("Tlatelolco", 1445), ("Autobuses del Norte", 975), ("Misterios", 892)], "intersections": ["linea5"]},
        "Tlatelolco": {"neighbors": [("La Raza", 1445), ("Guerrero", 1042)]},
        "Guerrero": {"neighbors": [("Tlatelolco", 1042), ("Hidalgo", 702), ("Garibaldi", 757), ("Buenavista", 521)], "intersections": ["lineaB"]},
        "Hidalgo": {"neighbors": [("Guerrero", 702), ("Juárez", 251), ("Revolución", 587), ("Bellas Artes", 447)], "intersections": ["linea2"]},
        "Juárez": {"neighbors": [("Hidalgo", 251), ("Balderas", 659)]},
        "Balderas": {"neighbors": [("Juárez", 659), ("Niños Héroes", 665), ("Cuauhtémoc", 409), ("Salto del Agua", 458)], "intersections": ["linea1"]},
        "Niños Héroes": {"neighbors": [("Balderas", 665), ("Hospital General", 559)]},
        "Hospital General": {"neighbors": [("Niños Héroes", 559), ("Centro Médico", 653)]},
        "Centro Médico": {"neighbors": [("Hospital General", 653), ("Etiopía/Plaza de la Transparencia", 1119), ("Lázaro Cárdenas", 1059), ("Chilpancingo", 1152)], "intersections": ["linea9"]},
        "Etiopía/Plaza de la Transparencia": {"neighbors": [("Centro Médico", 1119), ("Eugenia", 950)]},
        "Eugenia": {"neighbors": [("Etiopía/Plaza de la Transparencia", 950), ("División del Norte", 715)]},
        "División del Norte": {"neighbors": [("Eugenia", 715), ("Zapata", 794)]},
        "Zapata": {"neighbors": [("División del Norte", 794), ("Coyoacán", 1153), ("Parque de los Venados", 563), ("20 de Noviembre", 450)], "intersections": ["linea12"]},
        "Coyoacán": {"neighbors": [("Zapata", 1153), ("Viveros/Derechos Humanos", 908)]},
        "Viveros/Derechos Humanos": {"neighbors": [("Coyoacán", 908), ("Miguel Ángel de Quevedo", 824)]},
        "Miguel Ángel de Quevedo": {"neighbors": [("Viveros/Derechos Humanos", 824), ("Copilco", 1295)]},
        "Copilco": {"neighbors": [("Miguel Ángel de Quevedo", 1295), ("Universidad", 1306)]},
        "Universidad": {"neighbors": [("Copilco", 1306)]},
    },
    "linea4": {
        "Martín Carrera": {"neighbors": [("Talismán", 758), ("La Villa-Basílica", 1141)], "intersections": ["linea6"]},
        "Talismán": {"neighbors": [("Martín Carrera", 758), ("Bondojito", 1033)]},
        "Bondojito": {"neighbors": [("Talismán", 1033), ("Consulado", 633)]},
        "Consulado": {"neighbors": [("Bondojito", 633), ("Canal del Norte", 1062), ("Valle Gómez", 679), ("Eduardo Molina", 815)], "intersections": ["linea5"]},
        "Canal del Norte": {"neighbors": [("Consulado", 1062), ("Morelos", 910)]},
        "Morelos": {"neighbors": [("Canal del Norte", 910), ("Candelaria", 884), ("San Lázaro", 1296), ("Tepito", 498)], "intersections": ["lineaB"]},
        "Candelaria": {"neighbors": [("Morelos", 884), ("Fray Servando", 645), ("Merced", 698), ("San Lázaro", 866)], "intersections": ["linea1"]},
        "Fray Servando": {"neighbors": [("Candelaria", 645), ("Jamaica", 959)]},
        "Jamaica": {"neighbors": [("Fray Servando", 959), ("Santa Anita", 1129), ("Mixiuhca", 942), ("Chabacano", 1031)], "intersections": ["linea9"]},
        "Santa Anita": {"neighbors": [("Jamaica", 1129), ("La Viga", 633), ("Coyuya", 968)], "intersections": ["linea8"]},
    },
    "linea5": {
        "Politécnico": {"neighbors": [("Instituto del Petróleo", 1188)]},
        "Instituto del Petróleo": {"neighbors": [("Politécnico", 1188), ("Autobuses del Norte", 1067), ("Vallejo", 755), ("Lindavista", 1258)], "intersections": ["linea6"]},
        "Autobuses del Norte": {"neighbors": [("Instituto del Petróleo", 1067), ("La Raza", 975)]},
        "La Raza": {"neighbors": [("Autobuses del Norte", 975), ("Misterios", 892), ("Potrero", 1106), ("Tlatelolco", 1445)], "intersections": ["linea3"]},
        "Misterios": {"neighbors": [("La Raza", 892), ("Valle Gómez", 969)]},
        "Valle Gómez": {"neighbors": [("Misterios", 969), ("Consulado", 679)]},
        "Consulado": {"neighbors": [("Valle Gómez", 679), ("Eduardo Molina", 815), ("Bondojito", 633), ("Canal del Norte", 1062)], "intersections": ["linea4"]},
        "Eduardo Molina": {"neighbors": [("Consulado", 815), ("Aragón", 860)]},
        "Aragón": {"neighbors": [("Eduardo Molina", 860), ("Oceanía", 1219)]},
        "Oceanía": {"neighbors": [("Aragón", 1219), ("Terminal Aérea", 1174), ("Deportivo Oceanía", 863), ("Romero Rubio", 809)], "intersections": ["lineaB"]},
        "Terminal Aérea": {"neighbors": [("Oceanía", 1174), ("Hangares", 1153)]},
        "Hangares": {"neighbors": [("Terminal Aérea", 1153), ("Pantitlán", 1644)]},
        "Pantitlán": {"neighbors": [("Hangares", 1644), ("Zaragoza", 1320), ("Puebla", 1380), ("Agrícola Oriental", 1409)], "intersections": ["linea1", "linea9", "lineaA"]},
    },
    "linea6": {
        "El Rosario": {"neighbors": [("Tezozómoc", 1257), ("Aquiles Serdán", 1615)], "intersections": ["linea7"]},
        "Tezozómoc": {"neighbors": [("El Rosario", 1257), ("Azcapotzalco", 973)]},
        "Azcapotzalco": {"neighbors": [("Tezozómoc", 973), ("Ferrería/Arena Ciudad de México", 1173)]},
        "Ferrería/Arena Ciudad de México": {"neighbors": [("Azcapotzalco", 1173), ("Norte 45", 1072)]},
        "Norte 45": {"neighbors": [("Ferrería/Arena Ciudad de México", 1072), ("Vallejo", 660)]},
        "Vallejo": {"neighbors": [("Norte 45", 660), ("Instituto del Petróleo", 755)]},
        "Instituto del Petróleo": {"neighbors": [("Vallejo", 755), ("Lindavista", 1258), ("Politécnico", 1188), ("Autobuses del Norte", 1067)], "intersections": ["linea5"]},
        "Lindavista": {"neighbors": [("Instituto del Petróleo", 1258), ("Deportivo 18 de Marzo", 1075)]},
        "Deportivo 18 de Marzo": {"neighbors": [("Lindavista", 1075), ("La Villa-Basílica", 570), ("Indios Verdes", 1166), ("Potrero", 966)], "intersections": ["linea3"]},
        "La Villa-Basílica": {"neighbors": [("Deportivo 18 de Marzo", 570), ("Martín Carrera", 1141)]},
        "Martín Carrera": {"neighbors": [("La Villa-Basílica", 1141), ("Talismán", 758), ("Bondojito", 1033)], "intersections": ["linea4"]},
    },
    "linea7": {
        "El Rosario": {"neighbors": [("Aquiles Serdán", 1615), ("Tezozómoc", 1257)], "intersections": ["linea6"]},
        "Aquiles Serdán": {"neighbors": [("El Rosario", 1615), ("Camarones", 1402)]},
        "Camarones": {"neighbors": [("Aquiles Serdán", 1402), ("Refinería", 952)]},
        "Refinería": {"neighbors": [("Camarones", 952), ("Tacuba", 1295)]},
        "Tacuba": {"neighbors": [("Refinería", 1295), ("San Joaquín", 1433), ("Panteones", 1416), ("Cuitláhuac", 637)], "intersections": ["linea2"]},
        "San Joaquín": {"neighbors": [("Tacuba", 1433), ("Polanco", 1163)]},
        "Polanco": {"neighbors": [("San Joaquín", 1163), ("Auditorio", 812)]},
        "Auditorio": {"neighbors": [("Polanco", 812), ("Constituyentes", 1430)]},
        "Constituyentes": {"neighbors": [("Auditorio", 1430), ("Tacubaya", 1005)]},
        "Tacubaya": {"neighbors": [("Constituyentes", 1005), ("San Pedro de los Pinos", 1084), ("Observatorio", 1262), ("Juanacatlán", 1158), ("Patriotismo", 1133)], "intersections": ["linea1", "linea9"]},
        "San Pedro de los Pinos": {"neighbors": [("Tacubaya", 1084), ("San Antonio", 606)]},
        "San Antonio": {"neighbors": [("San Pedro de los Pinos", 606), ("Mixcoac", 788)]},
        "Mixcoac": {"neighbors": [("San Antonio", 788), ("Barranca del Muerto", 1476), ("Insurgentes Sur", 651)], "intersections": ["linea12"]},
        "Barranca del Muerto": {"neighbors": [("Mixcoac", 1476)]},
    },
    "linea8": {
        "Garibaldi / Lagunilla": {"neighbors": [("Bellas Artes", 634), ("Lagunilla", 474), ("Guerrero", 757)], "intersections": ["lineaB"]},
        "Bellas Artes": {"neighbors": [("Garibaldi / Lagunilla", 634), ("San Juan de Letrán", 456)], "intersections": ["linea2"]},#("Hidalgo", 447), ("Allende", 387)], 
        "San Juan de Letrán": {"neighbors": [("Bellas Artes", 456), ("Salto del Agua", 292)]},
        "Salto del Agua": {"neighbors": [("San Juan de Letrán", 292), ("Doctores", 564), ("Balderas", 458), ("Isabel la Católica", 445)], "intersections": ["linea1"]},
        "Doctores": {"neighbors": [("Salto del Agua", 564), ("Obrera", 761)]},
        "Obrera": {"neighbors": [("Doctores", 761), ("Chabacano", 1143)]},
        "Chabacano": {"neighbors": [("Obrera", 1143), ("La Viga", 843), ("San Antonio Abad", 642), ("Viaducto", 774), ("Lázaro Cárdenas", 1000), ("Jamaica", 1031)], "intersections": ["linea2", "linea9"]},
        "La Viga": {"neighbors": [("Chabacano", 843), ("Santa Anita", 633)]},
        "Santa Anita": {"neighbors": [("La Viga", 633), ("Coyuya", 968), ("Jamaica", 1129), ("Fray Servando", 959)], "intersections": ["linea4"]},
        "Coyuya": {"neighbors": [("Santa Anita", 968), ("Iztacalco", 993)]},
        "Iztacalco": {"neighbors": [("Coyuya", 993), ("Apatlaco", 910)]},
        "Apatlaco": {"neighbors": [("Iztacalco", 910), ("Aculco", 534)]},
        "Aculco": {"neighbors": [("Apatlaco", 534), ("Escuadrón 201", 789)]},
        "Escuadrón 201": {"neighbors": [("Aculco", 789), ("Atlalilco", 1738)]},
        "Atlalilco": {"neighbors": [("Escuadrón 201", 1738), ("Iztapalapa", 732), ("Culhuacán", 1671), ("Mexicaltzingo", 1922)], "intersections": ["linea12"]},
        "Iztapalapa": {"neighbors": [("Atlalilco", 732), ("Cerro de la Estrella", 717)]},
        "Cerro de la Estrella": {"neighbors": [("Iztapalapa", 717), ("UAM-I", 1135)]},
        "UAM-I": {"neighbors": [("Cerro de la Estrella", 1135), ("Constitución de 1917", 1137)]},
        "Constitución de 1917": {"neighbors": [("UAM-I", 1137)]},
    },
    "linea9": {
        "Pantitlán": {"neighbors": [("Puebla", 1380), ("Zaragoza", 1320), ("Hangares", 1644), ("Agrícola Oriental", 1409)], "intersections": ["linea1", "linea5", "lineaA"]},
        "Puebla": {"neighbors": [("Pantitlán", 1380), ("Ciudad Deportiva", 800)]},
        "Ciudad Deportiva": {"neighbors": [("Puebla", 800), ("Velódromo", 1110)]},
        "Velódromo": {"neighbors": [("Ciudad Deportiva", 1110), ("Mixiuhca", 821)]},
        "Mixiuhca": {"neighbors": [("Velódromo", 821), ("Jamaica", 942)]},
        "Jamaica": {"neighbors": [("Mixiuhca", 942), ("Chabacano", 1031), ("Fray Servando", 959), ("Santa Anita", 1129)], "intersections": ["linea4"]},
        "Chabacano": {"neighbors": [("Jamaica", 1031), ("Lázaro Cárdenas", 1000), ("San Antonio Abad", 642), ("Viaducto", 774), ("Obrera", 1143), ("La Viga", 843)], "intersections": ["linea2", "linea8"]},
        "Lázaro Cárdenas": {"neighbors": [("Chabacano", 1000), ("Centro Médico", 1059)]},
        "Centro Médico": {"neighbors": [("Lázaro Cárdenas", 1059), ("Chilpancingo", 1152), ("Hospital General", 653), ("Etiopía/Plaza de la Transparencia", 1119)], "intersections": ["linea3"]},
        "Chilpancingo": {"neighbors": [("Centro Médico", 1152), ("Patriotismo", 955)]},
        "Patriotismo": {"neighbors": [("Chilpancingo", 955), ("Tacubaya", 1133)]},
        "Tacubaya": {"neighbors": [("Patriotismo", 1133), ("Observatorio", 1262), ("Juanacatlán", 1158), ("Constituyentes", 1005), ("San Pedro de los Pinos", 1084)], "intersections": ["linea1", "linea7"]},
    },
    "lineaA": {
        "Pantitlán": {"neighbors": [("Agrícola Oriental", 1409), ("Zaragoza", 1320), ("Hangares", 1644), ("Puebla", 1380)], "intersections": ["linea1", "linea5", "linea9"]},
        "Agrícola Oriental": {"neighbors": [("Pantitlán", 1409), ("Canal de San Juan", 1093)]},
        "Canal de San Juan": {"neighbors": [("Agrícola Oriental", 1093), ("Tepalcates", 1456)]},
        "Tepalcates": {"neighbors": [("Canal de San Juan", 1456), ("Guelatao", 1161)]},
        "Guelatao": {"neighbors": [("Tepalcates", 1161), ("Peñón Viejo", 2206)]},
        "Peñón Viejo": {"neighbors": [("Guelatao", 2206), ("Acatitla", 1379)]},
        "Acatitla": {"neighbors": [("Peñón Viejo", 1379), ("Santa Marta", 1100)]},
        "Santa Marta": {"neighbors": [("Acatitla", 1100), ("Los Reyes", 1783)]},
        "Los Reyes": {"neighbors": [("Santa Marta", 1783), ("La Paz", 1956)]},
        "La Paz": {"neighbors": [("Los Reyes", 1956)]},
    },
    "lineaB": {
        "Ciudad Azteca": {"neighbors": [("Plaza Aragón", 574)]},
        "Plaza Aragón": {"neighbors": [("Ciudad Azteca", 574), ("Olímpica", 709)]},
        "Olímpica": {"neighbors": [("Plaza Aragón", 709), ("Ecatepec", 596)]},
        "Ecatepec": {"neighbors": [("Olímpica", 596), ("Múzquiz", 1485)]},
        "Múzquiz": {"neighbors": [("Ecatepec", 1485), ("Río de los Remedios", 1155)]},
        "Río de los Remedios": {"neighbors": [("Múzquiz", 1155), ("Impulsora", 436)]},
        "Impulsora": {"neighbors": [("Río de los Remedios", 436), ("Nezahualcóyotl", 1393)]},
        "Nezahualcóyotl": {"neighbors": [("Impulsora", 1393), ("Villa de Aragón", 1335)]},
        "Villa de Aragón": {"neighbors": [("Nezahualcóyotl", 1335), ("Bosque de Aragón", 784)]},
        "Bosque de Aragón": {"neighbors": [("Villa de Aragón", 1335), ("Deportivo Oceanía", 1165)]},
        "Deportivo Oceanía": {"neighbors": [("Bosque de Aragón", 1165), ("Oceanía", 863)]},
        "Oceanía": {"neighbors": [("Deportivo Oceanía", 863), ("Romero Rubio", 809), ("Aragón", 1219), ("Terminal Aérea", 1174)], "intersections": ["linea5"]},
        "Romero Rubio": {"neighbors": [("Oceanía", 809), ("Ricardo Flores Magón", 908)]},
        "Ricardo Flores Magón": {"neighbors": [("Romero Rubio", 908), ("San Lázaro", 907)]},
        "San Lázaro": {"neighbors": [("Ricardo Flores Magón", 907), ("Morelos", 1296), ("Candelaria", 866), ("Moctezuma", 478)], "intersections": ["linea1"]},
        "Morelos": {"neighbors": [("San Lázaro", 1296), ("Tepito", 498), ("Canal del Norte", 910), ("Candelaria", 884)], "intersections": ["linea4"]},
        "Tepito": {"neighbors": [("Morelos", 498), ("Lagunilla", 611)]},
        "Lagunilla": {"neighbors": [("Tepito", 611), ("Garibaldi", 474)]},
        "Garibaldi": {"neighbors": [("Lagunilla", 474), ("Guerrero", 757), ("Bellas Artes", 634)], "intersections": ["linea8"]},
        "Guerrero": {"neighbors": [("Garibaldi", 757), ("Buenavista", 521), ("Tlatelolco", 1042), ("Hidalgo", 702)], "intersections": ["linea3"]},
        "Buenavista": {"neighbors": [("Guerrero", 521)]},
    },
    "linea12": {
        "Tláhuac": {"neighbors": [("Tlaltenco", 1298)]},
        "Tlaltenco": {"neighbors": [("Tláhuac", 1298), ("Zapotitlán", 1115)]},
        "Zapotitlán": {"neighbors": [("Tlaltenco", 1115), ("Nopalera", 1276)]},
        "Nopalera": {"neighbors": [("Zapotitlán", 1276), ("Olivos", 1360)]},
        "Olivos": {"neighbors": [("Nopalera", 1360), ("Tezonco", 490)]},
        "Tezonco": {"neighbors": [("Olivos", 490), ("Periférico Oriente", 1545)]},
        "Periférico Oriente": {"neighbors": [("Tezonco", 1545), ("Calle 11", 1111)]},
        "Calle 11": {"neighbors": [("Periférico Oriente", 1111), ("Lomas Estrella", 906)]},
        "Lomas Estrella": {"neighbors": [("Calle 11", 906), ("San Andrés Tomatlán", 1060)]},
        "San Andrés Tomatlán": {"neighbors": [("Lomas Estrella", 1060), ("Culhuacán", 990)]},
        "Culhuacán": {"neighbors": [("San Andrés Tomatlán", 990), ("Atlalilco", 1671)]},
        "Atlalilco": {"neighbors": [("Culhuacán", 1671), ("Mexicaltzingo", 1922), ("Escuadrón 201", 1738), ("Iztapalapa", 732)], "intersections": ["linea8"]},
        "Mexicaltzingo": {"neighbors": [("Atlalilco", 1922), ("Ermita", 1805)]},
        "Ermita": {"neighbors": [("Mexicaltzingo", 1805), ("Eje Central", 895), ("Portales", 748), ("General Anaya", 838)], "intersections": ["linea2"]},
        "Eje Central": {"neighbors": [("Ermita", 895), ("Parque de los Venados", 1280)]},
        "Parque de los Venados": {"neighbors": [("Eje Central", 1280), ("Zapata", 563)]},
        "Zapata": {"neighbors": [("Parque de los Venados", 563), ("20 de Noviembre", 450), ("División del Norte", 794), ("Coyoacán", 1153)], "intersections": ["linea3"]},
        "20 de Noviembre": {"neighbors": [("Zapata", 450), ("Insurgentes Sur", 725)]},
        "Insurgentes Sur": {"neighbors": [("20 de Noviembre", 725), ("Mixcoac", 651)]},
        "Mixcoac": {"neighbors": [("Insurgentes Sur", 651), ("San Antonio", 788), ("Barranca del Muerto", 1476)], "intersections": ["linea7"]},
    }
}